// File generated by hand from Firebase Console config (no `flutterfire`
// CLI access in this environment — CLI needs an interactive Google login).
// Values: Android from `android/app/google-services.json`, Web from the
// config snippet the user pasted in chat on 2026-08-16. iOS not registered
// yet — add it here (and to ios/Runner via GoogleService-Info.plist) before
// shipping an iOS build.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS uchun Firebase hali sozlanmagan — GoogleService-Info.plist va '
          'ios konfiguratsiyasi kerak.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions.currentPlatform bu platforma uchun sozlanmagan — '
          '$defaultTargetPlatform',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpoABHuoERh6t8Xb-5mjRLcQ_bhTB3GN4',
    appId: '1:121326880937:web:60fef73264e9d2efb441b8',
    messagingSenderId: '121326880937',
    projectId: 'selta-cleaning',
    authDomain: 'selta-cleaning.firebaseapp.com',
    storageBucket: 'selta-cleaning.firebasestorage.app',
    measurementId: 'G-FQJY8SGDGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_sL-ho-h4W9aJ0VvkM40hhLm_Pl87pY',
    appId: '1:121326880937:android:f58b503a75d15b94b441b8',
    messagingSenderId: '121326880937',
    projectId: 'selta-cleaning',
    storageBucket: 'selta-cleaning.firebasestorage.app',
  );
}
